"""Shared category text blocks for prompts."""

# iPhone-specific categories (17 categories)
CATEGORIES_BULLETS = (
    "- battery_issue: Battery problems (draining fast, not charging, poor backup)\n"
    "- network_issue: Network/signal problems (weak WiFi, cellular, hotspot)\n"
    "- display_issue: Screen problems (defects, flickering, quality issues)\n"
    "- software_issue: Software problems (bugs, updates, iOS issues, hanging)\n"
    "- overheating: Device getting hot during use\n"
    "- sound_issue: Speaker/audio problems (low volume, distortion)\n"
    "- delivery_delay: Shipping/delivery took too long\n"
    "- wrong_item: Received incorrect product (wrong color, model)\n"
    "- poor_quality: General product quality issues (defective, broke easily)\n"
    "- damaged_packaging: Package or product arrived damaged\n"
    "- size_issue: Phone size complaints (too small screen, bezels)\n"
    "- missing_parts: Missing accessories (no charger, no earphones)\n"
    "- not_as_described: Product doesn't match listing/description\n"
    "- customer_service: Service/support issues (refund problems)\n"
    "- price_issue: Price-related complaints (too expensive)\n"
    "- positive_review: Actually positive review despite low rating\n"
    "- other: Cannot be categorized or extremely vague\n"
)

CATEGORIES_BULLETS_FINETUNE = (
    "- battery_issue: Battery problems\n"
    "- network_issue: Network/signal problems\n"
    "- display_issue: Screen problems\n"
    "- software_issue: Software problems\n"
    "- overheating: Device getting hot\n"
    "- sound_issue: Speaker/audio problems\n"
    "- delivery_delay: Shipping/delivery issues\n"
    "- wrong_item: Received incorrect product\n"
    "- poor_quality: Product quality problems\n"
    "- damaged_packaging: Damaged package or product\n"
    "- size_issue: Size-related issues\n"
    "- missing_parts: Missing parts or accessories\n"
    "- not_as_described: Product doesn't match description\n"
    "- customer_service: Customer service issues\n"
    "- price_issue: Price-related complaints\n"
    "- positive_review: Actually positive review\n"
    "- other: Cannot be categorized\n"
)
